server {
    listen 8081;
    listen [::]:8081;

    server_name 192.168.0.103;

    root /var/www/devops-hackathon-de001-hoangvanchung/src;
    index index.html;

    access_log /var/log/nginx/hoangvanchung-cntt1.access.log;
    error_log /var/log/nginx/hoangvanchung-cntt1.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
